### ISSUE TITLE
updates files in the destination dir. if needed

### ISSUE THREAD

**Issue by nicolo-tellini** [BioOmics/iSeq#11]
Dear @BioOmics ,

would it be possible or useful to add an option that updates files in the destination directories only if changes have occurred? For example, if the data in the database has been updated or modified, then download and update only those files, not the others - similar to how `rsync` uses the `--update` option.

thanks

nic

**Comment by BioOmics** [comment]
Dear @nicolo-tellini 

Thank you very much for your suggestion! iSeq may test this feature in the near future. However, I believe it might be a challenging task to implement, as it’s difficult to monitor high-throughput sequencing data for modifications in real-time. Additionally, the demand for repeatedly downloading updated high-throughput sequencing data might be relatively limited among our user base.

Therefore, this functionality may not be included in future updates—unless, of course, our testing goes exceptionally well.

Best regards

**Comment by nicolo-tellini** [comment]
Hi @BioOmics , 

OK :) thanks a lot for your comment, I close the issue. 

have a good day
