### ISSUE TITLE
ENA ascp批量下载卡停的问题

### ISSUE THREAD

**Issue by indexofire** [BioOmics/iSeq#12]
平时用脚本下ENA fastq, ascp经常会下一会就卡住。用iseq也出现类似的情况，是本地网络问题，还是ENA对于ascp有限制？

**Comment by BioOmics** [comment]
大概率是公共数据库实时吞吐量有波动。我也遇到过，但是卡住之后过一会就会自己恢复，速度会再慢慢上来。

下载ENA的数据，可以直接下载，不加-a参数有时候也很快，另外多线程下载-p有时候也比ascp快很多。

祝好

**Comment by BioOmics** [comment]
如果您有其他问题，欢迎再次打开本issue

**Comment by indexofire** [comment]
反复测试了，我这里ENA ascp下载确实会卡，而且非常频繁，下几个到几十个数据时就会卡停，必须ctrl+c中断掉继续下载下一个。如果别人没有遇到，可能是我自己这里的问题。

**Comment by littlelight-hhr** [comment]
我也遇到了，请问有好的解决办法吗？

**Comment by BioOmics** [comment]
这个问题还挺频繁出现的，目前没有很好的解决方案，如果想完全规避尽量不要使用ascp(也就是不使用-a参数)，直接通过http或者ftp下载，速度应该也不慢
