### ISSUE TITLE
error for iseq -a（iseq -i ERR9606776   -g  -p 16 -a）

### ISSUE THREAD

**Issue by bio-shun** [BioOmics/iSeq#13]
(iSeq) [user@rlab coral-sra]$ iseq -i ERR9606776   -g  -p 16 -a
Note: -a and -p options were used at the same time, -a will be used first
      ERR9606776_1.fastq.gz 8.83G 	       ERR9606776_2.fastq.gz 10.28G 	 
Note: Above Run will be downloaded. You can see the details in ERR9606776.metadata.tsv
Note: -g used, download FASTQ files in gzip format directly
File size: 8.83G	Database: ENA	Mode: Aspera
ascp: Private key file not found at path /home/user/.ssh/-QT and path /home/user/.ssh/-QT, exiting.

Session Stop  (Error: Private key file not found at path /home/user/.ssh/-QT and path /home/user/.ssh/-QT)
File size: 10.28G	Database: ENA	Mode: Aspera
ascp: Private key file not found at path /home/user/.ssh/-QT and path /home/user/.ssh/-QT, exiting.

Session Stop  (Error: Private key file not found at path /home/user/.ssh/-QT and path /home/user/.ssh/-QT)
Note: ERR9606776 validate failed, retry 1 times
Note: -g used, download FASTQ files in gzip format directly
File size: 8.83G	Database: ENA	Mode: Aspera
ascp: Private key file not found at path /home/user/.ssh/-QT and path /home/user/.ssh/-QT, exiting.

Session Stop  (Error: Private key file not found at path /home/user/.ssh/-QT and path /homeuser/.ssh/-QT)
File size: 10.28G	Database: ENA	Mode: Aspera
ascp: Private key file not found at path /home/user/.ssh/-QT and path /home/user/.ssh/-QT, exiting.

Session Stop  (Error: Private key file not found at path /home/user/.ssh/-QT and path /home/user/.ssh/-QT)
Note: ERR9606776 validate failed, remove the file and retry 2 times
Note: -g used, download FASTQ files in gzip format directly
File size: 8.83G	Database: ENA	Mode: Aspera
ascp: Private key file not found at path /home/user/.ssh/-QT and path /home/user/.ssh/-QT, exiting.

Session Stop  (Error: Private key file not found at path /home/user/.ssh/-QT and path /home/user/.ssh/-QT)
File size: 10.28G	Database: ENA	Mode: Aspera
ascp: Private key file not found at path /home/user/.ssh/-QT and path /home/user/.ssh/-QT, exiting.

Session Stop  (Error: Private key file not found at path /home/user/.ssh/-QT and path /home/user/.ssh/-QT)
ERR9606776 md5 check failed after trying 3 times, save Run ID in fail.log
=====================================================ERR9606776 download finished=====================================================

then, I create the dir: 

(iSeq) [user@lab coral-sra]$ mkdir -p ~/.ssh/-QT/
(iSeq) [user@lab coral-sra]$ cd ~/.ssh/-QT/
(iSeq) [user@lab -QT]$ cp ~/.conda/envs/iSeq/
bin/             docs/            include/         lib64/           product-info.mf  share/           
conda-meta/      etc/             lib/             man/             sbin/            ssl/             
(iSeq) [user@lab -QT]$ cp ~/.conda/envs/iSeq/etc/
aspera.conf               aspera_tokenauth_id_rsa   asperaweb_id_dsa.putty    curl-ca-bundle.crt        wgetrc
aspera-license            asperaweb_id_dsa.openssh  conda/                    gemrc                     
(iSeq) [user@lab -QT]$ ln -s  ~/.conda/envs/iSeq/etc/* ~/.ssh/
(iSeq) [user@lab -QT]$ ln -s  ~/.conda/envs/iSeq/etc/* ~/.ssh/-QT/
(iSeq) [user@lab -QT]$ iseq -i ERR9606776   -g  -p 16 -a
Note: -a and -p options were used at the same time, -a will be used first
      ERR9606776_1.fastq.gz 8.83G 	       ERR9606776_2.fastq.gz 10.28G 	 
Note: Above Run will be downloaded. You can see the details in ERR9606776.metadata.tsv
Note: -g used, download FASTQ files in gzip format directly
File size: 8.83G	Database: ENA	Mode: Aspera
ascp: failed to authenticate, exiting.

Session Stop  (Error: failed to authenticate)
File size: 10.28G	Database: ENA	Mode: Aspera
ascp: failed to authenticate, exiting.

Session Stop  (Error: failed to authenticate)
Note: ERR9606776 validate failed, retry 1 times
Note: -g used, download FASTQ files in gzip format directly
File size: 8.83G	Database: ENA	Mode: Aspera
ascp: failed to authenticate, exiting.

Session Stop  (Error: failed to authenticate)
File size: 10.28G	Database: ENA	Mode: Aspera
ascp: failed to authenticate, exiting.

Session Stop  (Error: failed to authenticate)
Note: ERR9606776 validate failed, remove the file and retry 2 times
Note: -g used, download FASTQ files in gzip format directly
File size: 8.83G	Database: ENA	Mode: Aspera
ascp: failed to authenticate, exiting.

Session Stop  (Error: failed to authenticate)
File size: 10.28G	Database: ENA	Mode: Aspera
ascp: failed to authenticate, exiting.

Session Stop  (Error: failed to authenticate)
ERR9606776 md5 check failed after trying 3 times, save Run ID in fail.log
=====================================================ERR9606776 download finished=====================================================

How can I solution this problem？please！！！！
best wish

**Comment by BioOmics** [comment]
Hi, @bio-shun 

Translate to English: Try to reinstall iSeq using conda without installing Aspera manually, as iSeq has already packaged it.
Additionally, do not use both -a and -p at the same time, as they correspond to different download methods.
For the Session Stop (Error: failed to authenticate) error, if you still encounter issues after reinstalling iSeq, you can 1. try multiple times at different times, 2. check your server's network issues, and also, firewalls could potentially affect it.

Best

**Comment by bio-shun** [comment]
thanks for your reply! 
I test  again " iseq -i ERR9606776 -g  -a" not any problem!!!!!
best wish!
