### ISSUE TITLE
Problems with single-end sequencing downloads

### ISSUE THREAD

**Issue by Dx-wmc** [BioOmics/iSeq#16]
Hi, I've noticed that iseq has no problem downloading double-ended sequencing from ena, but none of the gz files downloaded from single-ended sequencing can be unzipped. The gz files I get using the ftp download address prompted in iseq unzip just fine, is something wrong?

**Comment by BioOmics** [comment]
Can you give me the code you used?

**Comment by Dx-wmc** [comment]
The command I used is "iseq -i SRR18030918  -g -t 20 -p 1 -o ."

**Comment by BioOmics** [comment]
Now, you can try the latest version, [iSeq v1.4.0](https://github.com/BioOmics/iSeq/releases/tag/v1.4.0) (Also can be installed by Bioconda later). Thank you again for pointing out the issues.
