### ISSUE TITLE
Double-ended data download and MD5 verification issues

### ISSUE THREAD

**Issue by longxy0121** [BioOmics/iSeq#17]
![微信图片_20241205173444](https://github.com/user-attachments/assets/f1782185-9e45-484c-8736-9917bbc1edee)
One end of the paired-end sequencing data was not completely downloaded, but the check and md5 tests passed and were written to the success.log file. This shouldn't be right.

**Comment by BioOmics** [comment]
Now, you can try the latest version, [iSeq v1.4.0](https://github.com/BioOmics/iSeq/releases/tag/v1.4.0) (Also can be installed by Bioconda later). Thank you again for pointing out the issues.
