### ISSUE TITLE
select data generated with a specific sequencing platform and or RNA/DNA

### ISSUE THREAD

**Issue by nicolo-tellini** [BioOmics/iSeq#18]
Hi,

Would it be possible to implement an option that allows users to select specific sequencing strategies for download?

For example, de novo genome assembly often requires diverse sequencing reads from platforms like PacBio, ONT, and Illumina. In some cases, not all of these are needed for a particular analysis. 

Can RNA/DNA be partitioned or selectively chosen given a project code?

thank you

**Comment by BioOmics** [comment]
This is easy to implement, but considering that PacBio, ONT, and Illumina have different SRRs, you can use SRRs to distinguish and download these datasets separately.  
Therefore, the best approach is for users to manually filter the information in the metadata before using it. For example:  
First, use iSeq to retrieve metadata information (NIP rice T2T project):  
```bash
$ iseq -i PRJNA953663 -m
```

Then filter: 
```bash
$ grep "Hi-C" PRJNA953663.metadata.tsv | cut -f1
SRR25241089
$ grep "ONT" PRJNA953663.metadata.tsv | cut -f1
SRR25241091
$ grep "hifi" PRJNA953663.metadata.tsv | cut -f1 
SRR25241090
```
Then download:  
```bash
$ grep "ONT" PRJNA953663.metadata.tsv | cut -f1 | xargs -I {} iseq -i {}
      SRR25241091	69.48G
Note: Above Run will be downloaded. You can see the details in SRR25241091.metadata.tsv
.....
```

Therefore, iSeq may not add this feature or might add a `--filter` option in the future to specify filtering criteria. However, doing so may lead to some unforeseen issues.  
Hope this helps you!

**Comment by nicolo-tellini** [comment]
Hello,

yes! thanks a lot for the support.

I close the issue

Have a good day
