### ISSUE TITLE
=2.11.0

### ISSUE THREAD

**Issue by nicolo-tellini** [BioOmics/iSeq#19]
Hi, 

I am using latest version. When I run the tool, iseq creates a file in my home named '=2.11.0'.

best

nic

**Comment by BioOmics** [comment]
Hi,

Now, you can try the latest version, [iSeq v1.5.0](https://github.com/BioOmics/iSeq/releases/tag/v1.5.0) (Also can be installed or updated by Bioconda later). Thank you again for pointing out the issues.

Bset

**Comment by nicolo-tellini** [comment]
many thanks 

nic
