### ISSUE TITLE
merging by sample name 

### ISSUE THREAD

**Issue by nicolo-tellini** [BioOmics/iSeq#2]
Dear @BioOmics ,

is there any option for merging fastqs based on sample ID instead of experiment ID?

thanks 

best 

nic

**Comment by BioOmics** [comment]
Dear @nicolo-tellini , 

Thank you for using iSeq. I apologize that currently iSeq does not have parameters to support the merging of Sample IDs. However, I am aware of another software that can fulfill your requirements, and that is [fastq-dl](https://github.com/rpetit3/fastq-dl).

Best

**Comment by nicolo-tellini** [comment]
@BioOmics 

What do you think about it as a new feature to implement?
