### ISSUE TITLE
Possible dependency version change for sra-tools

### ISSUE THREAD

**Issue by dhanyajagan** [BioOmics/iSeq#3]
dear @BioOmics, 

Wanted to kindly ask if the dependency version requirement for sra-tools=2.11.0 can be upgraded to 3.1.1? Reason is that I keep running into errors with fasterq-dump when trying to download .gz fastq files.

Thanks!

**Comment by BioOmics** [comment]
Dear @dhanyajagan ,

In fact, you can update the version of `sra-tools` without affecting the use of `iSeq`. See the code below:

```bash
conda update -c bioconda sra-tools=3.1.1
```

Additionally, could you share your running code with me? Under normal circumstances, `fasterq-dump` should not be affected by the version of `sra-tools`.

Best

**Comment by BioOmics** [comment]
I will close the issue now. If you have any questions, please feel free to open it again

**Comment by Sotdo** [comment]
The requirement of the sra-tools is still limited to 2.11.0 in version 1.1.

```
mamba create -n iseq_latest sra-tools=3.1.1 iseq=1.1.0 -c bioconda -c conda-forge

Looking for: ['sra-tools=3.1.1', 'iseq=1.1.0']

r/linux-64                                                    No change
bioconda/noarch                                               No change
bioconda/linux-64                                             No change
r/noarch                                                      No change
pkgs/r/linux-64                                               No change
pkgs/main/noarch                                              No change
pkgs/main/linux-64                                            No change
pkgs/r/noarch                                                 No change
conda-forge/noarch                                  16.7MB @ 528.7kB/s 31.5s
conda-forge/linux-64                                38.5MB @ 646.3kB/s 59.6s
Could not solve for environment specs
The following packages are incompatible
├─ iseq 1.1.0**  is installable and it requires
│  └─ sra-tools 2.11.0.* , which can be installed;
└─ sra-tools 3.1.1**  is not installable because it conflicts with any installable versions previously reported.
```

**Comment by BioOmics** [comment]
Hi

Now, we update the dependency version requirement for sra-tools=2.11.0 to >=2.11.0, you can try [v1.2.0](https://anaconda.org/bioconda/iseq), thank your suggestion!

Best
