### ISSUE TITLE
Some questions regarding the download process and Aspera settings.

### ISSUE THREAD

**Issue by zhanxiangzong** [BioOmics/iSeq#7]
Hello, thank you for providing this user-friendly tool; it has been very helpful for our data analysis, but I have encountered some issues during its use.

（1）Tasks that are terminated during the download process are also recorded in success.log. I used ctrl+c to terminate the task during the download, but the returned message still indicated "SRR1301040 download and md5 check successful" with the following log:
`[  2%] [0           .1           2            3            4            5            6            7            ] [   1.4MB/s] [09:27]
Downloaded 15.9246 Megabyte(s) in 10 second(s). (1482.78 KB/s)
md5sum: SRR1301040.fastq.gz: No such file or directory
SRR1301040 download and md5 check successful, save SRR1301040 in success.log
Note: SRR1301041 FASTQ file is also not available in the ENA database, switch to download SRA file
Note: SRA database used, will download SRA file and convert to FASTQ file in gzip format
`
（2）When data is temporarily inaccessible (e.g., network issues resulting in 0.00 B/s), the task does not automatically stop or switch to querying other databases; instead, it keeps trying indefinitely (or I may not have observed long enough).
（3）I wonder if it’s possible to add a parameter to specify the location of the Aspera key file and to limit the download speed, which would be useful when using iSeq on public servers.
（4）Additionally, the MD5 checksum fails when I download data from GSA.

I look forward to your reply and would like to express my gratitude again

**Comment by BioOmics** [comment]
Thank you for using iSeq and for your suggestions:

（1）I have monitored certain programs in the code to check if they execute completely, like $? -eq 0. There might be some omissions. Could you provide the complete code for me to test?

（2）Currently, iSeq uses wget, axel, and aspera, which do not have similar functionalities. This may require manual termination and re-downloading. Additionally, I recommend running the same code again after completing the data download to effectively identify any missing data.

（3）This is a good suggestion, and I plan to add this option in version 1.2. For now, you can manually modify the code at line 317 in the script [L317](https://github.com/BioOmics/iSeq/blob/4f4634d6d136d76cd58439747e75a1ce11935af4/bin/iseq#L317).

（4）Could you share the code with me? So far, my tests have been successful.

 ---
感谢您使用 iSeq并提供建议：

（1）我在程序中监控了某些程序是否完整执行，如 $? -eq 0，可能存在遗漏的地方。您能否提供完整的代码，以便我进行测试？

（2）目前 iSeq 调用的是 wget、axel 和 aspera，这三个软件没有类似的功能，因此可能需要手动终止再重新下载。此外，我建议在完成数据下载后，再次执行相同的代码，以有效排查遗漏的数据。

（3）这是一个很好的建议，我计划在 1.2 版本中增加这个选项。目前，您可以手动修改代码，在脚本的 317 行 [L317](https://github.com/BioOmics/iSeq/blob/4f4634d6d136d76cd58439747e75a1ce11935af4/bin/iseq#L317)。

（4）您能把代码分享给我吗？目前我测试是正常的。

**Comment by zhanxiangzong** [comment]
Thank you for your response. Today, I repeated the previous steps and found that I was able to successfully complete the data download and validation. It seems that the earlier error might have been related to my network environment.

**Comment by BioOmics** [comment]
Hi

Now, you can try [v1.2.0](https://anaconda.org/bioconda/iseq), we add a `-s`, `--speed` option to set the download speed limit (MB/s) (default: 1000 MB/s). Such as `iseq -i SRR7706354 -s 10`

Best

**Comment by zhanxiangzong** [comment]
Thank you so much for implementing this feature; it’s incredibly useful. I do have a small question, though. In public clusters, networked nodes are often restricted from running compute tasks, which means I’m unable to use certain data processing functions provided by iseq, such as SRA conversions and data merging. Would it be possible for iseq to offer a standalone data processing module, separate from the download module? This would be a huge help for handling large-scale omics data in public clusters.
Thanks again, and looking forward to your response!

**Comment by BioOmics** [comment]
In fact, you can use the same code to execute specific processing functions, as iSeq will skip parts that have already been processed.

For example 1, if I have a file named SRR7706354 in my current folder and I want to perform SRA conversions, I can run:
```bash
iseq -i SRR7706354 -q
```
iSeq will skip downloading SRR7706354 (since it's already done) and proceed directly to SRA conversions.

---
For example 2, if I have CRR022335.fastq.gz and CRR022336.fastq.gz (both Runs are from CRX020217) in my current folder and I want to merge them, I can run:
```bash
iseq -i CRX020217 -e ex
```
iSeq will skip downloading CRR022335 and CRR022336 and directly proceed to merge them.

You can give it a try, and if you have any issues, feel free to ask again.

**Comment by BioOmics** [comment]
If you have any other issues, feel free to reopen this issue at any time.
