### ISSUE TITLE
What 'key passphrase' and 'password' should I enter when downloading SRR on NCBI

### ISSUE THREAD

**Issue by hyd-zju** [BioOmics/iSeq#8]
Hi! @BioOmics 
Thanks a lot for providing this helpful tool, which really bringing us much convenience.
Recently, I met a problom when using code '-a' to download SRR1178105.
`~$ iseq -i SRR1178105 -a
      SRR1178105        0.27G
Note: Above Run will be downloaded. You can see the details in SRR1178105.metadata.tsv
File size: 0.27G        Database: ENA   Mode: Aspera
Key passphrase:
Password:`
It kept reminding me of the 'Key passphrase' and 'Password', but I had no idea what they are.
Looking forward to your reply.

Best wishes

hyd

**Comment by BioOmics** [comment]
Thanks

I was able to download successfully by running the same code; you can retry or update to the latest version v1.1
![image](https://github.com/user-attachments/assets/3aae640b-7941-44b5-9adb-87a0d6a72322)

Best

**Comment by BioOmics** [comment]
If have any questions, please open it again.
